In [1]:
import numpy as np

input = np.array([i for i in range(1, 10)])

weights = np.array([
    [i for i in range(1, 10)],
    [i for i in range(1, 10)],
    [i for i in range(1, 10)],
]).T

print(input)
print(weights)

print(input.dot(weights))

[1 2 3 4 5 6 7 8 9]
[[1 1 1]
 [2 2 2]
 [3 3 3]
 [4 4 4]
 [5 5 5]
 [6 6 6]
 [7 7 7]
 [8 8 8]
 [9 9 9]]
[285 285 285]


In [2]:
input = [f"x{i}" for i in range(9)]
input

['x1', 'x2', 'x3', 'x4', 'x5', 'x6', 'x7', 'x8', 'x9']

In [6]:
weights = []

for i in range(9):
    row = [f"y{j}/{i}" for j in range(3)]
    weights.append(row)

weights

[['y0/0', 'y1/0', 'y2/0'],
 ['y0/1', 'y1/1', 'y2/1'],
 ['y0/2', 'y1/2', 'y2/2'],
 ['y0/3', 'y1/3', 'y2/3'],
 ['y0/4', 'y1/4', 'y2/4'],
 ['y0/5', 'y1/5', 'y2/5'],
 ['y0/6', 'y1/6', 'y2/6'],
 ['y0/7', 'y1/7', 'y2/7'],
 ['y0/8', 'y1/8', 'y2/8']]

In [10]:
MULTIPLIER_COUNT = 4